import { useSQLiteContext } from 'expo-sqlite';
import { createContext, PropsWithChildren, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import type { Account, Budget, Category, EntryType, Transaction } from '@/data/types';
export type TransactionInput = Omit<Transaction, 'id'>;
export type CategoryInput = Omit<Category, 'id'>;
export type AccountInput = Omit<Account, 'id'>;
export type BudgetInput = Omit<Budget, 'id'>;
type MoneyContextValue = { accounts: Account[]; categories: Category[]; transactions: Transaction[]; budgets: Budget[]; loading: boolean; currency: string; username: string; onboardingCompleted: boolean; addTransaction: (transaction: TransactionInput) => Promise<void>; saveTransaction: (input: TransactionInput, id?: string) => Promise<void>; deleteTransaction: (id: string) => Promise<void>; saveCategory: (input: CategoryInput, id?: string) => Promise<void>; deleteCategory: (id: string) => Promise<boolean>; saveAccount: (input: AccountInput, id?: string) => Promise<void>; deleteAccount: (id: string) => Promise<boolean>; saveBudget: (input: BudgetInput, id?: string) => Promise<void>; deleteBudget: (id: string) => Promise<void>; setGlobalCurrency: (currency: string) => Promise<void>; setGlobalUsername: (name: string) => Promise<void>; completeOnboarding: () => Promise<void>; };
const createUniqueId = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const MoneyContext = createContext<MoneyContextValue | null>(null);
export function MoneyProvider({ children }: PropsWithChildren) {
  const db = useSQLiteContext(); const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [budgets, setBudgets] = useState<Budget[]>([]); const [loading, setLoading] = useState(true);
  const [currency, setCurrency] = useState('USD'); const [username, setUsername] = useState('User'); const [onboardingCompleted, setOnboardingCompleted] = useState(false);
  const refresh = useCallback(async () => { const [a, c, t, b, s] = await Promise.all([db.getAllAsync<Account>('SELECT * FROM accounts ORDER BY name'), db.getAllAsync<Category>('SELECT * FROM categories ORDER BY type, name'), db.getAllAsync<Transaction>('SELECT * FROM transactions ORDER BY date DESC'), db.getAllAsync<Budget>('SELECT * FROM budgets ORDER BY month DESC'), db.getAllAsync<{key: string, value: string}>('SELECT * FROM settings')]); setAccounts(a); setCategories(c); setTransactions(t); setBudgets(b); const cur = s.find((x) => x.key === 'currency')?.value; if (cur) setCurrency(cur); const uname = s.find((x) => x.key === 'username')?.value; if (uname) setUsername(uname); const onb = s.find((x) => x.key === 'onboarding')?.value; if (onb === '1') setOnboardingCompleted(true); setLoading(false); }, [db]);
  useEffect(() => { refresh(); }, [refresh]);
  const saveTransaction = useCallback(async (transaction: TransactionInput, id?: string) => { await db.withTransactionAsync(async () => { if (id) { const previous = await db.getFirstAsync<Transaction>('SELECT * FROM transactions WHERE id = ?', id); if (!previous) throw new Error('Transaction not found'); const undoSource = previous.type === 'income' ? -previous.amount : previous.amount; await db.runAsync('UPDATE accounts SET balance = balance + ? WHERE id = ?', undoSource, previous.accountId); if (previous.type === 'transfer' && previous.toAccountId) await db.runAsync('UPDATE accounts SET balance = balance - ? WHERE id = ?', previous.amount, previous.toAccountId); await db.runAsync('UPDATE transactions SET type = ?, accountId = ?, toAccountId = ?, categoryId = ?, amount = ?, date = ?, note = ?, receiptUri = ? WHERE id = ?', transaction.type, transaction.accountId, transaction.toAccountId ?? null, transaction.categoryId ?? null, transaction.amount, transaction.date, transaction.note ?? null, transaction.receiptUri ?? null, id); } else { id = createUniqueId('tx'); await db.runAsync('INSERT INTO transactions (id, type, accountId, toAccountId, categoryId, amount, date, note, receiptUri) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', id, transaction.type, transaction.accountId, transaction.toAccountId ?? null, transaction.categoryId ?? null, transaction.amount, transaction.date, transaction.note ?? null, transaction.receiptUri ?? null); } const sourceImpact = transaction.type === 'income' ? transaction.amount : -transaction.amount; await db.runAsync('UPDATE accounts SET balance = balance + ? WHERE id = ?', sourceImpact, transaction.accountId); if (transaction.type === 'transfer' && transaction.toAccountId) await db.runAsync('UPDATE accounts SET balance = balance + ? WHERE id = ?', transaction.amount, transaction.toAccountId); }); await refresh(); }, [db, refresh]);
  const addTransaction = useCallback(async (transaction: TransactionInput) => saveTransaction(transaction), [saveTransaction]);
  const deleteTransaction = useCallback(async (id: string) => { await db.withTransactionAsync(async () => { const previous = await db.getFirstAsync<Transaction>('SELECT * FROM transactions WHERE id = ?', id); if (!previous) return; const undoSource = previous.type === 'income' ? -previous.amount : previous.amount; await db.runAsync('UPDATE accounts SET balance = balance + ? WHERE id = ?', undoSource, previous.accountId); if (previous.type === 'transfer' && previous.toAccountId) await db.runAsync('UPDATE accounts SET balance = balance - ? WHERE id = ?', previous.amount, previous.toAccountId); await db.runAsync('DELETE FROM transactions WHERE id = ?', id); }); await refresh(); }, [db, refresh]);
  const saveCategory = useCallback(async (input: CategoryInput, id?: string) => { if (id) await db.runAsync('UPDATE categories SET name = ?, type = ?, icon = ?, color = ? WHERE id = ?', input.name, input.type, input.icon, input.color, id); else await db.runAsync('INSERT INTO categories (id, name, type, icon, color) VALUES (?, ?, ?, ?, ?)', createUniqueId('category'), input.name, input.type, input.icon, input.color); await refresh(); }, [db, refresh]);
  const deleteCategory = useCallback(async (id: string) => { if (transactions.some((transaction) => transaction.categoryId === id)) return false; await db.runAsync('DELETE FROM categories WHERE id = ?', id); await refresh(); return true; }, [db, refresh, transactions]);
  const saveAccount = useCallback(async (input: AccountInput, id?: string) => { if (id) await db.runAsync('UPDATE accounts SET name = ?, type = ?, balance = ?, currency = ? WHERE id = ?', input.name, input.type, input.balance, input.currency, id); else await db.runAsync('INSERT INTO accounts (id, name, type, balance, currency) VALUES (?, ?, ?, ?, ?)', createUniqueId('account'), input.name, input.type, input.balance, input.currency); await refresh(); }, [db, refresh]);
  const deleteAccount = useCallback(async (id: string) => { if (transactions.some((transaction) => transaction.accountId === id || transaction.toAccountId === id)) return false; await db.runAsync('DELETE FROM accounts WHERE id = ?', id); await refresh(); return true; }, [db, refresh, transactions]);
  const saveBudget = useCallback(async (input: BudgetInput, id?: string) => { const budgetId = id ?? 'budget-' + input.categoryId + '-' + input.month; await db.runAsync('INSERT INTO budgets (id, categoryId, amount, month) VALUES (?, ?, ?, ?) ON CONFLICT(categoryId, month) DO UPDATE SET amount = excluded.amount', budgetId, input.categoryId, input.amount, input.month); await refresh(); }, [db, refresh]);
  const deleteBudget = useCallback(async (id: string) => { await db.runAsync('DELETE FROM budgets WHERE id = ?', id); await refresh(); }, [db, refresh]);
  const setGlobalCurrency = useCallback(async (val: string) => { await db.runAsync('INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value', 'currency', val); await refresh(); }, [db, refresh]);
  const setGlobalUsername = useCallback(async (val: string) => { await db.runAsync('INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value', 'username', val); await refresh(); }, [db, refresh]);
  const completeOnboarding = useCallback(async () => { await db.runAsync('INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value', 'onboarding', '1'); await refresh(); }, [db, refresh]);
  return <MoneyContext.Provider value={useMemo(() => ({ accounts, categories, transactions, budgets, loading, currency, username, onboardingCompleted, addTransaction, saveTransaction, deleteTransaction, saveCategory, deleteCategory, saveAccount, deleteAccount, saveBudget, deleteBudget, setGlobalCurrency, setGlobalUsername, completeOnboarding }), [accounts, categories, transactions, budgets, loading, currency, username, onboardingCompleted, addTransaction, saveTransaction, deleteTransaction, saveCategory, deleteCategory, saveAccount, deleteAccount, saveBudget, deleteBudget, setGlobalCurrency, setGlobalUsername, completeOnboarding])}>{children}</MoneyContext.Provider>;
}
export function useMoney() { const value = useContext(MoneyContext); if (!value) throw new Error('useMoney must be used within MoneyProvider'); return value; }
export function categoryFor(categories: Category[], id?: string | null) { return categories.find((category) => category.id === id); }
export function totalFor(transactions: Transaction[], type: EntryType) { return transactions.filter((transaction) => transaction.type === type).reduce((sum, transaction) => sum + transaction.amount, 0); }
